//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to copy the selected files?.
        /// </summary>
        public static string dialogCopy {
            get {
                return ResourceManager.GetString("dialogCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to create a new folder?.
        /// </summary>
        public static string dialogCreateFolder {
            get {
                return ResourceManager.GetString("dialogCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DirectoryDate {
            get {
                return ResourceManager.GetString("DirectoryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext..
        /// </summary>
        public static string DirectoryExtension {
            get {
                return ResourceManager.GetString("DirectoryExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DirectoryName {
            get {
                return ResourceManager.GetString("DirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string DirectorySize {
            get {
                return ResourceManager.GetString("DirectorySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string DirectoryVersion {
            get {
                return ResourceManager.GetString("DirectoryVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder already exists!.
        /// </summary>
        public static string FolderAlreadyExists {
            get {
                return ResourceManager.GetString("FolderAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Kirk {
            get {
                object obj = ResourceManager.GetObject("Kirk", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;All.
        /// </summary>
        public static string MenuAll {
            get {
                return ResourceManager.GetString("MenuAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        public static string MenuCopy {
            get {
                return ResourceManager.GetString("MenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create &amp;Folder.
        /// </summary>
        public static string MenuCreateFolder {
            get {
                return ResourceManager.GetString("MenuCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        public static string MenuDelete {
            get {
                return ResourceManager.GetString("MenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Developer Tools.
        /// </summary>
        public static string MenuDeveloperTools {
            get {
                return ResourceManager.GetString("MenuDeveloperTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Favourites.
        /// </summary>
        public static string MenuFavourites {
            get {
                return ResourceManager.GetString("MenuFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Fullscreen.
        /// </summary>
        public static string MenuFullscreen {
            get {
                return ResourceManager.GetString("MenuFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Move.
        /// </summary>
        public static string MenuMove {
            get {
                return ResourceManager.GetString("MenuMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Navigation.
        /// </summary>
        public static string MenuNavigation {
            get {
                return ResourceManager.GetString("MenuNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Preview.
        /// </summary>
        public static string MenuPreview {
            get {
                return ResourceManager.GetString("MenuPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Properties.
        /// </summary>
        public static string MenuProperties {
            get {
                return ResourceManager.GetString("MenuProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Refresh.
        /// </summary>
        public static string MenuRefresh {
            get {
                return ResourceManager.GetString("MenuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rename.
        /// </summary>
        public static string MenuRename {
            get {
                return ResourceManager.GetString("MenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open same folder.
        /// </summary>
        public static string MenuSameFolder {
            get {
                return ResourceManager.GetString("MenuSameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Selection.
        /// </summary>
        public static string MenuSelection {
            get {
                return ResourceManager.GetString("MenuSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;Hidden.
        /// </summary>
        public static string MenuShowHidden {
            get {
                return ResourceManager.GetString("MenuShowHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Blue.
        /// </summary>
        public static string MenuThemeBlue {
            get {
                return ResourceManager.GetString("MenuThemeBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Dark.
        /// </summary>
        public static string MenuThemeDark {
            get {
                return ResourceManager.GetString("MenuThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Light Blue.
        /// </summary>
        public static string MenuThemeLightBlue {
            get {
                return ResourceManager.GetString("MenuThemeLightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Themes.
        /// </summary>
        public static string MenuThemes {
            get {
                return ResourceManager.GetString("MenuThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Unselect All.
        /// </summary>
        public static string MenuUnselectAll {
            get {
                return ResourceManager.GetString("MenuUnselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Zoom.
        /// </summary>
        public static string MenuZoom {
            get {
                return ResourceManager.GetString("MenuZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string RootLabel {
            get {
                return ResourceManager.GetString("RootLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string RootName {
            get {
                return ResourceManager.GetString("RootName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string RootSize {
            get {
                return ResourceManager.GetString("RootSize", resourceCulture);
            }
        }
    }
}
